### ISSUE TITLE
Won't work

### ISSUE THREAD

**Issue by affibox** [yupferris/fuse-example-android-foreign-code-basics#1]
All i get is "module not found"

**Comment by yupferris** [comment]
I've just tried locally with Fuse 0.24, and I had no such issue. Can you please provide any more information so I can help you out? Which OS are you running on? Which device are you using? Did you follow our [Android setup instructions](https://www.fusetools.com/docs/basics/preview-and-export#android-setup)? Are you trying to preview on PC or on the device?

**Comment by affibox** [comment]
OS: Windows 10
Device: Android Galaxy Note 7
Did you follow our Android setup instructions?: Yup. Most of my app is running on the device.
Are you trying to preview on PC or on the device?: Device. I know Foreign code won't run on the PC Simulator.

**Comment by affibox** [comment]
Is there anything else I have to do to be able to import the UNO code?

**Comment by yupferris** [comment]
Did you add the `.uno` file to the `Includes` section of your `.unproj` file? https://www.fusetools.com/docs/native-interop/native-interop#adding-uno-files-to-a-project

**Comment by yupferris** [comment]
I realize that may not have been clear from the video or the docs it linked to; perhaps that's something we can fix.

**Comment by affibox** [comment]
It is not clear.... Maybe that's the problem

**Comment by yupferris** [comment]
Please try it out and let me know what you find. Also, if you could try cloning this repo and let me know if that works, that would help as well so we can try and isolate what the problem is.

**Comment by affibox** [comment]
Cloning the project worked but  this ### "Did you add the .uno file to the Includes section of your .unproj file? https://www.fusetools.com/docs/native-interop/native-interop#adding-uno-files-to-a-project"
Didn't

**Comment by affibox** [comment]
![image](https://cloud.githubusercontent.com/assets/8114543/17977081/3515e154-6abe-11e6-8a9d-9a14ae389252.png)

**Comment by affibox** [comment]
I manage to make it work. 

The error some how was this line: `<SystemSounds ux:Global="SystemSounds" />`

After adding the line everything worked.

But the docs are still misleading and needs to be clarify

**Comment by yupferris** [comment]
Glad you got it working! I've already made tickets internally for us to fix this issue in the doc's. Thanks for reporting!
